'use client';

import localFont from 'next/font/local';
import './globals.css';
import { Roboto } from 'next/font/google';
import { NhostProvider } from '@nhost/nextjs';
import nhost from '@/utils/nhost';
import { NhostApolloProvider } from '@nhost/react-apollo';
import { usePathname } from 'next/navigation';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

// const metadata = {
// 	title: 'Books App',
// 	description: 'Generated by create next app',
// };

// function FrozenRouter(props) {
// 	const context = useContext(LayoutRouterContext);
// 	const frozen = useRef(context).current;

// 	return (
// 		<LayoutRouterContext.Provider value={frozen}>
// 			{props.children}
// 		</LayoutRouterContext.Provider>
// 	);
// }

export default function RootLayout({ children }) {
	// const pathname = usePathnamethname();

	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}>
				<NhostProvider nhost={nhost}>
					<NhostApolloProvider
						nhost={nhost}
						graphqlUrl='https://fjxyezhyddcwejusthlr.hasura.eu-west-2.nhost.run/v1/graphql'>
						{/* <AnimatePresence> */}
						<div
							className='w-full h-full '
							// key={pathname}
							// initial={{ opacity: 0 }}
							// animate={{ opacity: 1 }}
							// exit={{ opacity: 0 }}
							// transition={{ type: 'spring', bounce: 0.3 }}
						>
							{/* <FrozenRouter> */}
							{children}
							{/* </FrozenRouter> */}
						</div>
						{/* </AnimatePresence> */}
					</NhostApolloProvider>
				</NhostProvider>
			</body>
		</html>
	);
}
